name: Shellcheck

on:
  push:
    paths:
      - "scripts/**"
  pull_request:
    paths:
      - "scripts/**"

jobs:
  shellcheck:
    name: Lint bash scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck on all scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
          severity: warning